export const accountGroups = [
    "Assets",
    "Liabilities",
    "Equity",
    "Income",
    "Expenses",
    "Current Assets",
    "Current Liabilities",
    "Fixed Assets",
    "Bank Accounts",
    "Cash-in-hand",
    "Sundry Debtors",
    "Sundry Creditors",
    "Loans (Liabilities)",
    "Capital Account",
    "Sales Accounts",
    "Purchase Accounts",
    "Direct Expenses",
    "Indirect Expenses",
    "Direct Incomes",
    "Indirect Incomes",
    "Suspense A/c",
];