export const accountGroups = [
    { label: "Assets", value: "assets" },
    { label: "Liabilities", value: "liabilities" },
    { label: "Equity", value: "equity" },
    { label: "Income", value: "income" },
    { label: "Expenses", value: "expenses" },
    { label: "Current Assets", value: "current_assets" },
    { label: "Current Liabilities", value: "current_liabilities" },
    { label: "Fixed Assets", value: "fixed_assets" },
    { label: "Bank Accounts", value: "bank_accounts" },
    { label: "Cash-in-hand", value: "cash_in_hand" },
    { label: "Sundry Debtors", value: "sundry_debtors" },
    { label: "Sundry Creditors", value: "sundry_creditors" },
    { label: "Loans (Liabilities)", value: "loans_liabilities" },
    { label: "Capital Account", value: "capital_account" },
    { label: "Sales Accounts", value: "sales_accounts" },
    { label: "Purchase Accounts", value: "purchase_accounts" },
    { label: "Direct Expenses", value: "direct_expenses" },
    { label: "Indirect Expenses", value: "indirect_expenses" },
    { label: "Direct Incomes", value: "direct_incomes" },
    { label: "Indirect Incomes", value: "indirect_incomes" },
    { label: "Suspense A/c", value: "suspense_a_c" }
];