export const statesAndCodes = [
    { state: "Andaman and Nicobar Islands", code: "35" },
    { state: "Andhra Pradesh", code: "28" },
    { state: "Arunachal Pradesh", code: "12" },
    { state: "Assam", code: "18" },
    { state: "Bihar", code: "10" },
    { state: "Chandigarh", code: "04" },
    { state: "Chhattisgarh", code: "22" },
    { state: "Dadra and Nagar Haveli and Daman and Diu", code: "26" },
    { state: "Delhi", code: "07" },
    { state: "Goa", code: "30" },
    { state: "Gujarat", code: "24" },
    { state: "Haryana", code: "06" },
    { state: "Himachal Pradesh", code: "02" },
    { state: "Jammu and Kashmir", code: "01" },
    { state: "Jharkhand", code: "20" },
    { state: "Karnataka", code: "29" },
    { state: "Kerala", code: "32" },
    { state: "Ladakh", code: "37" },
    { state: "Lakshadweep", code: "31" },
    { state: "Madhya Pradesh", code: "23" },
    { state: "Maharashtra", code: "27" },
    { state: "Manipur", code: "14" },
    { state: "Meghalaya", code: "17" },
    { state: "Mizoram", code: "15" },
    { state: "Nagaland", code: "13" },
    { state: "Odisha", code: "21" },
    { state: "Puducherry", code: "34" },
    { state: "Punjab", code: "03" },
    { state: "Rajasthan", code: "08" },
    { state: "Sikkim", code: "11" },
    { state: "Tamil Nadu", code: "33" },
    { state: "Telangana", code: "36" },
    { state: "Tripura", code: "16" },
    { state: "Uttar Pradesh", code: "09" },
    { state: "Uttarakhand", code: "05" },
    { state: "West Bengal", code: "19" }
];